### ISSUE TITLE
Add Support for Typescript Compilation

### ISSUE THREAD

**Issue by helloimalastair** [helloimalastair/WorkerOnReplit#1]
Currently, the build pipeline does not natively support Type-Checking. This can be added with TSC, as recommended [here](https://esbuild.github.io/content-types/#typescript). Along with adding TSC to the `package.json`, documentation should be added to the [README](..) to help people convert their Repl from JS mode to TS mode.

**Comment by shazm12** [comment]
hi ,I have one question like are u asking like a way to be able to migrate the project from JS to TS?

**Comment by helloimalastair** [comment]
> hi ,I have one question like are u asking like a way to be able to migrate the project from JS to TS?

Not really. More like adding support for people to easily build and test an application for Workers written in TS. Currently, to be able to run the test, the script in the `src` folder is bundled into a singular file, which can then be run. This bundled file must be Javascript, and not Typescript. The bundler I am using has support for compiling Typescript, but does not support Type Checking. This Issue was written to address that, so that people who do you Typescript can check their types before their code is built and tested.

**Comment by shazm12** [comment]
ohh okay will try to look for a solution to the mentioned problem and get back to you thanks for explaining the issue.

**Comment by helloimalastair** [comment]
> ohh okay will try to look for a solution to the mentioned problem and get back to you thanks for explaining the issue.

Thank you @shazm12! Assigned you to this issue!

**Comment by shazm12** [comment]
hey @helloimalastair do you have sources to get more info about it?

**Comment by helloimalastair** [comment]
> hey @helloimalastair do you have sources to get more info about it?
Sources for Typescript, or Esbuild?

**Comment by shazm12** [comment]
No, it's fine I found one article regarding the issue. Can you plz check my PR?

**Comment by shazm12** [comment]
hey @helloimalastair just one request that can you add 'hacktoberfest-accepted' as the label to the PR as this PR is showing that it will not be accepted in the hacktoberfest.

Thank you!

**Comment by helloimalastair** [comment]
> 
> 
> hey @helloimalastair just one request that can you add 'hacktoberfest-accepted' as the label to the PR as this PR is showing that it will not be accepted in the hacktoberfest.
> 
> Thank you!

Of course, just waiting for your final approval on the changes I suggested to your code, then it will be merged, and I will add the tag to the PR.
